name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y
      - name: Start LocalStack with Docker Compose
        run: docker-compose up -d  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: Run pylint
        run: | 
          pylint --fail-under 7 app
          exitcode="$?"
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          exit "$exitcode"
      - name: Run unit tests
        run: |
          pytest tests/test_unit.py --maxfail=1 --disable-warnings -v
      - name: Run integration tests
        run: |
          pytest tests/test_integration.py --maxfail=1 --disable-warnings -v
      - name: Run BDD tests
        run: |
          pip install behave
          behave tests/features
      - name: Run coverage
        run: |
          coverage run -m pytest && coverage report -m
      - name: Teardown Docker
        if: always()
        run: docker-compose down
      - name: Send email on success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "CI Success: ${{ github.repository }}"
          body: "The CI pipeline for ${{ github.repository }} has completed successfully!"
          to: your.email@example.com
          from: ${{ secrets.SMTP_USERNAME }}
      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "CI Failure: ${{ github.repository }}"
          body: "The CI pipeline for ${{ github.repository }} has failed. Check the logs for details."
          to: your.email@example.com
          from: ${{ secrets.SMTP_USERNAME }}